config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get "admin", to: "pages#admin"
    resources :gardens do
      resources :garden_plants, only: %i[new create update destroy]
    end
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user, ->(user) { user.vip? } do
    get "vip", to: "pages#vip"
    resources :gardens
    resources :tasks
  end

  devise_for :users

  root to: "pages#home"
  resources :pages, only: %i[home merci]

  resources :gardens do
    resources :garden_plants, only: [:create, :destroy] do
    end
  end

  resources :plants, only: [] do
    resources :reviews, only: %i[new create]
  end

  resources :tasks, only: [:index] do
    member do
      patch :update_done
      patch :update_tasks
    end
  end

  # resources :payments, only: [:new, :create]
  resources :garden_plants, only: %i[show destroy update]
  resources :tasks, only: [:update]
  resources :pages, only: %i[home cover]

  # Cette route sert à prévenir l'utilisateur que sa région n'est pas supportée par l'app en ce moment.
  get "gardens/:id/unsupported_region", to: "gardens#unsupported_region", as: :unsupported_region

  post "gardens/:id/validate_plants", to: "gardens#validate_plants", as: :validate_plants_garden
  get "gardens/:id/select_plants", to: "gardens#select_plants", as: :select_plants
  get "gardens/:id/crush", to: "gardens#crush", as: :crush

  # Ces routes sont utilisées après la validation des crushes afin de demander les infos de livraison et le code d'achat
  # de l'utilisateur.
  get "users/:id/delivery_info", to: "registrations#edit_delivery_info", as: :edit_delivery_info
  patch "users/:id", to: "registrations#update_delivery_info", as: :update_delivery_info

  # Cette route envoie l'utilisateur sur une page de remerciement après avoir pris ses coordonnées.
  get "users/:id/merci", to: "pages#merci", as: :merci
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_garden_plant_task_label.html.erb
<div class="garden-plant-card-label">
  <%= cl_image_tag task.plant.photo.key, class: "avatar" %>
  <p><%= task.garden_plant.nickname %></p>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <!--<%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'gorillaz_canopee.png', class: "avatar-large" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item">
            <%# <%= link_to "Plants", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               <span class="navbar-toggler-icon"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
               <% if user_signed_in? %>
                    <a href="<%= edit_user_registration_path %>">Account</a>
                    <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                    <%# <i class="fa-solid fa-bars"></i> %>
                <% else %>
                    <%= link_to "Sign In", new_user_session_path, class:"navbar-item, btn btn-warning" %>
                    <%= link_to "Sign up", new_user_registration_path, class:"navbar-item, btn btn-warning"%>
                <% end %>
      </ul>
    </div>-->
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<div class="navbar-bottom-container">
  <div class="navbar-bottom align-items-center d-flex justify-content-around">
    <%= link_to root_path do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
    <%= link_to gardens_path do %>
      <i class="fa-solid fa-seedling"></i>
    <% end %>
    <% if user_signed_in?%>
      <%= link_to tasks_path do %>
        <% @notifications.each do |notification| %>
          <% if notification.unread? %>
            <div class="notification-dot blinking"></div>
          <% end %>
        <% end %>
        <i class="fa-solid fa-heart"></i>
      <% end %>
    <% else %>
      <i class="fa-solid fa-heart"></i>
    <% end %>
    <% if user_signed_in?%>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr de vouloir vous déconnecter ?"} do%>
        <i class="fa-solid fa-user"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fa-solid fa-user"></i>
      <% end %>
    <% end %>
  </div>
</div>