config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get "admin", to: "pages#admin"
    resources :gardens do
      resources :garden_plants, only: %i[new create update destroy]
    end
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user, ->(user) { user.vip? } do
    get "vip", to: "pages#vip"
    resources :gardens
    resources :tasks
  end

  devise_for :users

  root to: "pages#home"
  resources :pages, only: %i[home merci]

  resources :gardens do
    resources :garden_plants, only: [:create, :destroy] do
    end
  end

  resources :plants, only: [] do
    resources :reviews, only: %i[new create]
  end

  resources :tasks, only: [:index] do
    member do
      patch :update_done
      patch :update_tasks
    end
  end

  # resources :payments, only: [:new, :create]
  resources :garden_plants, only: %i[show destroy update]
  resources :tasks, only: [:update]
  resources :pages, only: %i[home cover]

  # Cette route sert à prévenir l'utilisateur que sa région n'est pas supportée par l'app en ce moment.
  get "gardens/:id/unsupported_region", to: "gardens#unsupported_region", as: :unsupported_region

  post "gardens/:id/validate_plants", to: "gardens#validate_plants", as: :validate_plants_garden
  get "gardens/:id/select_plants", to: "gardens#select_plants", as: :select_plants
  get "gardens/:id/crush", to: "gardens#crush", as: :crush

  # Ces routes sont utilisées après la validation des crushes afin de demander les infos de livraison et le code d'achat
  # de l'utilisateur.
  get "users/:id/delivery_info", to: "registrations#edit_delivery_info", as: :edit_delivery_info
  patch "users/:id", to: "registrations#update_delivery_info", as: :update_delivery_info

  # Cette route envoie l'utilisateur sur une page de remerciement après avoir pris ses coordonnées.
  get "users/:id/merci", to: "pages#merci", as: :merci
end

app/models/garden_plant.rb
class GardenPlant < ApplicationRecord
  NICKNAMES = ["Paulette", "Diane", "Célia", "Julia", "Germain", "Baptiste", "Adonis", "Helena", "Alexandra", "Lucie", "Lesly", "Jules", "Robert", "Michel", "Georgette", "Agathe", "Francis", "Hubert", "Patrick", "Nathalie", "Patricia", "Louise", "Jane", "Luc", "Maria", "Joe", "Julio", "Julliette", "Elvis"]

  belongs_to :plant
  belongs_to :garden
  has_one :user, through: :garden

  has_many :tasks, dependent: :destroy

  # validates :nickname, uniqueness: { scope: :garden_id }
  # validates :pot_color, inclusion: {in: %w()}

  after_update :create_initial_tasks
  after_create_commit :set_nickname

  enum :status, {
    pre_selected: 0,
    refused: 5,
    selected: 10,
    validated: 20
  }


  def score
    urgence = 0
    tasks = self.tasks
    tasks.each do |task|
      if task.completion_date.nil?
        urgence += task.criticity.to_i * 10
      end
    end
    if urgence < 50 && urgence > 0
      return 50 - urgence
    else
      return 100 - urgence
    end
  end

  private

  def create_initial_tasks
    return unless validated?

    create_initial_repotting_task
    create_initial_watering_task
  end

  def create_initial_repotting_task
    if plant.growth_speed.zero?
      Task.create(activity: 'Rempote-moi !',
                  criticity: 0,
                  start_time: DateTime.now + 1.year,
                  due_date: DateTime.now + 1.year + 1.week,
                  garden_plant: self,
                  user: garden.user)
    elsif plant.growth_speed == 1
      Task.create(activity: 'Rempote-moi !',
                  criticity: 0,
                  start_time: DateTime.now + 2.year,
                  due_date: DateTime.now + 2.year + 1.week,
                  garden_plant: self,
                  user: garden.user)
    elsif plant.growth_speed == 2
      Task.create(activity: 'Rempote-moi !',
                  criticity: 0,
                  start_time: DateTime.now + 3.year,
                  due_date: DateTime.now + 3.year + 1.week,
                  garden_plant: self,
                  user: garden.user)
    end
  end

  def create_initial_watering_task
    Task.create(activity: 'Arrose-moi !',
                criticity: 2,
                start_time: DateTime.now,
                due_date: DateTime.now + 1.day,
                garden_plant: self,
                user: garden.user)
  end

  def set_nickname
    available_nicknames = NICKNAMES.reject do |nickname|
      garden.garden_plants.select(:nickname).include?(nickname)
    end
    self.nickname = available_nicknames.sample
    save
  end
end

app/controllers/garden_plants_controller.rb
class GardenPlantsController < ApplicationController
  before_action :set_garden_plant, only: [:show, :edit, :update, :destroy]


  def index
    @garden_plants = current_user.garden_plants
    @garden_plants = @garden.garden_plants
  end

  def show
  end


  def new
    @garden_plant = @garden.garden_plants.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @garden_plant = @garden_plants.new(garden_plant_params)
    @garden_plant.garden = @garden
    if @garden_plant.save
      redirect_to garden_plant_path(@garden_plant), notice: 'Jardin créé avec succès'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @garden_plant.update(garden_plant_params)
      @garden = @garden_plant.garden
      finished = @garden.number_of_remaining_plants == 0
      respond_to do |format|
        format.json { render json: { garden_plant_count: @garden.number_of_selected_plants, remaining_plants: @garden.number_of_remaining_plants, finished: finished, garden_crush_path: crush_path(@garden) } }
        format.html { redirect_to garden_plant_path(@garden_plant), notice: 'Garden plant was successfully updated.'}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @garden_plant.destroy
    redirect_to garden_path(@garden_plant.garden), notice: 'Garden plant was successfully destroyed.' if @garden_plant.validated?
    redirect_to crush_path(@garden_plant.garden), notice: 'Garden plant was successfully destroyed.' if @garden_plant.selected?
  end

  private

  def set_garden_plant
    @garden_plant = GardenPlant.find(params[:id])
  end

  def garden_plant_params
    params.require(:garden_plant).permit(:nickname, :pot_color, :plant_id, :status)
  end
end

app/views/garden_plants/_garden_plant.html.erb
<div class="container">
  <div class= row>
    <div class="col 3 p-3">
      <div class="mb3 bc-secondary">
        <div class="card-body">
            <h4><%= garden_plant.nickname %></h4>
            <p>Pot Color: <%= garden_plant.pot_color %></p>
            <p>Plant: <%= garden_plant.plant.name %></p>
            <p>Garden: <%= garden_plant.garden.name %></p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/garden_plants/_review_card.html.erb
<div class="review__card"
    data-review-target="card"
    data-id="<%= @garden_plant.id %>"
    data-bs-toggle="offcanvas"
    data-bs-target="#offcanvas-<%= @garden_plant.id%>">
       <span><h6>Lire plus sur mon histoire</h6></span>
</div>


<div class="offcanvas offcanvas-bottom offcanvas-plant-info" tabindex="-1" id="offcanvas-<%= @garden_plant.id %>">
  <div class="offcanvas-header">
    <%# <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button> %>
    <h5><%= @garden_plant.nickname %></h5>
  </div>
  <div class="offcanvas-body small">
    <%= cl_image_tag @garden_plant.plant.photo.key, class: 'modal_content__img' if @garden_plant.plant.photo.attached? %>

    <p><%= @garden_plant.plant.content %></p>
  </div>
</div>

app/views/garden_plants/_select_card.html.erb
<div class="plant-option">
  <%= cl_image_tag garden_plant.plant.photo.key %>
  <p><%= garden_plant.plant.name %></p>
</div>

app/views/garden_plants/new.html.erb
<h1>NEW ardenPlant </h1>

<%= render 'form', garden_plant: @garden_plant %>

app/views/garden_plants/show.html.erb
 <div class="d-flex flex-column min-full-screen bg-dark-green">
  <div class="garden-plant-image" style="margin-bottom: -72px;">
    <%= cl_image_tag @garden_plant.plant.photo.key, class:"image-card" %>
  </div>
  <div class="info-card flex-grow-1-1-0">
    <div class="container text-center mt-3">
      <h1><%= @garden_plant.nickname %></h1>
      <p> J’ai grandi en Ile de France chez Maurice Boyauval mon horticulteur. </p>
      <h4><%= @garden_plant.plant.name %></h4>
      <hr>
      <h5> <%= render "review_card" %></h5> <br>
        <div class="health-bar-container">
          <div class="health-bar"
                style="
                  width:<%= @garden_plant.score %>%;
                  background-color: <%= color_level(@garden_plant.score) %>;
                ">
          </div>
            <span class="health-bar-score">
              <%= @garden_plant.score %>%
            </span>
          </div>
          <span> </span>

        </div>

        <div class="tasks-list">
          <% @garden_plant.tasks.near_future.each do |task| %>
              <%# if task.completion_date.nil? && task.due_date.year == Time.now.year && task.due_date.month == Time.now.month %>
                <div class="mb-2">
                  <%= simple_form_for task, url: update_done_task_path(task) , method: :patch, html: { class:"form-activitiy" } do |f| %>
                    <p class="m-0 form-left"><%= task.activity %></p>
                    <div class="form-center">
                      <%= button_tag class: "btn-fait d-flex justify-content-center align-items-center" do %>
                        <i class="fa-solid fa-check"></i>
                      <% end %>
                    </div>
                    <p class="m-0 form-right"><%= task.due_date.day%>/<%= task.due_date.month %>/<%= task.due_date.year %></p>
                  <% end %>
                </div>
              <%# end %>

          <% end %>
        </div>


      <div class="filler bg-dark-green">
      <%= link_to 'Retour à mes plantes', garden_path(@garden_plant.garden), class: "back d-block mt-5 text-center" %>
      </div>
  </div>
</div>