config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get "admin", to: "pages#admin"
    resources :gardens do
      resources :garden_plants, only: %i[new create update destroy]
    end
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user, ->(user) { user.vip? } do
    get "vip", to: "pages#vip"
    resources :gardens
    resources :tasks
  end

  devise_for :users

  root to: "pages#home"
  resources :pages, only: %i[home merci]

  resources :gardens do
    resources :garden_plants, only: [:create, :destroy] do
    end
  end

  resources :plants, only: [] do
    resources :reviews, only: %i[new create]
  end

  resources :tasks, only: [:index] do
    member do
      patch :update_done
      patch :update_tasks
    end
  end

  # resources :payments, only: [:new, :create]
  resources :garden_plants, only: %i[show destroy update]
  resources :tasks, only: [:update]
  resources :pages, only: %i[home cover]

  # Cette route sert à prévenir l'utilisateur que sa région n'est pas supportée par l'app en ce moment.
  get "gardens/:id/unsupported_region", to: "gardens#unsupported_region", as: :unsupported_region

  post "gardens/:id/validate_plants", to: "gardens#validate_plants", as: :validate_plants_garden
  get "gardens/:id/select_plants", to: "gardens#select_plants", as: :select_plants
  get "gardens/:id/crush", to: "gardens#crush", as: :crush

  # Ces routes sont utilisées après la validation des crushes afin de demander les infos de livraison et le code d'achat
  # de l'utilisateur.
  get "users/:id/delivery_info", to: "registrations#edit_delivery_info", as: :edit_delivery_info
  patch "users/:id", to: "registrations#update_delivery_info", as: :update_delivery_info

  # Cette route envoie l'utilisateur sur une page de remerciement après avoir pris ses coordonnées.
  get "users/:id/merci", to: "pages#merci", as: :merci
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_plant, only: [ :index, :new, :create, :show ]

  def index
    @reviews = Review.find(params[:plant_id])
  end

  def new
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.plant = Plant.find(params[:plant_id])
    @review.save
    redirect_to plant_path(@plant.garden)
  end

  def show
    @review = Review.find(params[:plant_id])
  end


  private

  def review_params
    params.require(:review).permit(:content, :note)
  end

  def set_plant
    @plant = Plant.find(params[:plant_id])
  end
end

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<%= simple_form_for [@plant, @review] do |f| %>
  <%= f.association() %>
  <%= f.submit 'Add!' %>
<% end %>

app/views/reviews/show.html.erb
<div class="container">
  <h2 class="plant-show-name"><%= @plant.name %></h2>
  <p class="review-description">Nos amoureux des plantes en parlent !</p>
  <div class="row">
    <% @review.garden_plants.plant.each do |review| %>
        <%= link_to garden_plant_path(garden_plant), class: 'garden-plant-card' do %>
          <div class='d-flex'>
            <div class="col-6 nickname-and-life-bar">
              <h3 class='plant-nickname'><%= garden_plant.nickname %></h3>
              <div class='life-bar'>
                <div class='current-life'></div>
                <div class='max-life'></div>
              </div>
            </div>
            <div class="col-6">
              <%= cl_image_tag garden_plant.plant.photo.key, width: 183, class: "image-card" %>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
  <%= link_to 'Retour aux jardins', gardens_path, class: "btn btn-primary" %>
  <%= link_to 'Supprimer le jardin', garden_path(@garden), class: "btn btn-warning", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }%>
</div>